#!/bin/sh
### Hey, Yeah, You! Your awesome! Keep being yourself, thanks a ton for using BlurME! BlurME is dedicated to You!
wall="$HOME/wallpaper2.png"
wp_blur="./output.png"
wp="$wall"
while getopts ":w:b:c:" opt
do
  case "$opt" in
    w ) wid=$OPTARG;;
    b ) blur=$OPTARG;;
    c ) wp=$OPTAGR;;

  esac 
done
while sleep 1
do
echo "$wp"
echo Bluring with scale of "$blur"
if [ -z "$wp" ]; then
    echo "No wallpaper set"
    echo echo "Use '-c'"
    exit 1
else
    echo "Wallpaper is $wp"
fi
if [ "$blur" -ge "2" ]; then
    convert "$wp" -blur 0x"$blur" ./output.png
    wp_blur=./output.png
else
    echo "'-b' not used!?"
    echo "Segfault"
    exit 1
fi
if [ "$XDG_CURRENT_DESKTOP" = "KDE" ]; then
    lswK=$(lsw | wc -l)
    echo "$lswK Windows/Widgets Are Open"
    if [ -n "$wid" ]; then
        echo "Widget Amount is $wid"
    else
        wid="2"
    fi
if [ "$lswK" -le "$wid" ]; then
    echo "Setting Non-Blurred Wallpaper"
    qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wp}'")}'
  else
    if [ "$lswK" = "1" ]; then
      echo "Setting Non-Blurred Wallpaper"
      qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wp}'")}'
    else 
      echo "Blurring"
      qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wp_blur}'")}'
    fi
  fi
else
  if [ "$DESKTOP_SESSION" = "/usr/share/xsessions/plasma" ]; then
    lswK=$(lsw | wc -l)
    if [ -n "$wid" ]; then
      echo "Widget Amount is $wid"
    else 
      wid="2"
    fi
    if [ "$lswK" -le "$wid" ]; then
      echo "Setting Non-Blurred Wallpaper"
      qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wall}'")}'
    else
      if [ "$lswK" = "1" ]; then
        echo "Setting Non-Blurred Wallpaper"
        qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wall}'")}'
      else 
        echo "Blurring"
        qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file://'${wp_blur}'")}'
      fi
    fi
  else
    while sleep 1
    lswK=$(lsw | wc -l)
    do
        if [ "$lswK" -le "$wid" ];
        then
            echo "$lswK Windows are open"
            echo "Max number of windows is $wid"
            echo "Setting no blured wallpaper"
            feh --bg-fill "$wall"
        else
            echo "Max window number is $wid"
            echo "current is $lswK"
            echo "Bluring"
            feh --bg-fill "$wp_blur"
        fi
    done
  fi
fi
done
